services:
  - type: web
    name: txt 750 extractor 
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/yassuhacks750/TXT-750-EXTRACTOR
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: OWNER
        sync: false
      - key: CREDIT
        sync: false
      #- key: WEBHOOK
        #sync: false
      - key: PORT
        value: 8000  # Default port value, update if neede
        
